version: '3.8'
services:
  backend-hackaton:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    networks:
      - app-network
    depends_on:
      - postgres
    command: sh -c "npm install && npm run start:dev"